### ISSUE TITLE
Mouse area option doesn't work

### ISSUE THREAD

**Issue by dragonxtek** [drpain/blink-server#15]
When I enable Mouse Area and I tried move the mouse, the app crashed.
I got this message:

`COMMAND RECEIVED [{"action":"mouse-move","x":null,"y":null}{"action":"mouse-move","x":-25.349761962890625,"y":-32.430633544921875}]
[MULTIPLE COMMANDS] This may work, this may not work

Traceback (most recent call last):
  File "bluetooth_server.py", line 42, in <module>
    commandKeys(data)
  File "blink-server/core.py", line 58, in commandKeys
    commandKeys(command)
  File "blink-server/core.py", line 96, in commandKeys
    str(float(JSON['x'])),
TypeError: float() argument must be a string or a number`

I'm using Ubuntu 18.10

**Comment by Rudis1261** [comment]
Cool will have a look

**Comment by KarNair** [comment]
I got the same error on ubuntu 18.04

**Comment by lyiriyah** [comment]
any updates @drpain? am having this issue too.

**Comment by Rudis1261** [comment]
Hey guys, I can make it a bit more robust, but ultimately I am not actively developing this. I have mentioned a couple of times. I have been using Apple for a number of years now, and windows as my home PC.

**Comment by Rudis1261** [comment]
@lyiriyah Can you pull the latest version and see if that helps you?
