### ISSUE TITLE
Adding --compat didn't work

### ISSUE THREAD

**Issue by bitnom** [drpain/blink-server#4]
On Ubuntu 16.04 I modified `/lib/systemd/system/bluetooth.service` to show `ExecStart=/usr/lib/bluetooth/bluetoothd --compat` and then restarted bluetooth but still same error 

```
Traceback (most recent call last):
  File "bluetooth_server.py", line 25, in <module>
    profiles         = [ SERIAL_PORT_PROFILE ]
  File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 176, in advertise_service
    raise BluetoothError (str (e))
```

and `service bluetooth status` shows:

```
 bluetoothd[27411]: Not enough free handles to register service
 bluetoothd[27411]: Not enough free handles to register service
 bluetoothd[27411]: Current Time Service could not be registered
bluetoothd[27411]: gatt-time-server: Input/output error (5)
 bluetoothd[27411]: Not enough free handles to register service
 bluetoothd[27411]: Not enough free handles to register service
 bluetoothd[27411]: Sap driver initialization failed.
 bluetoothd[27411]: sap-server: Operation not permitted (1)
 bluetoothd[27411]: Endpoint registered: sender=:1.51 path=/MediaEndpoint/A2DPSour
 bluetoothd[27411]: Endpoint registered: sender=:1.51 path=/MediaEndpoint/A2DPSink
```

My other bluetooth devices are working.

**Comment by Rudis1261** [comment]
Hmmm `bluetoothd[27411]: Not enough free handles to register service` that is a bit concerning. Were you able to find a resolution? 

I have never run into this particular issue myself sadly

**Comment by Cxarli** [comment]
I added `--compat` and it did work for me (`5.2.11-1-MANJARO`). My output of `systemctl status bluetooth` shows:

```
$ sudo systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-10-06 19:01:58 CEST; 32min ago
     Docs: man:bluetoothd(8)
 Main PID: 20958 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   Memory: 1.8M
   CGroup: /system.slice/bluetooth.service
           └─20958 /usr/lib/bluetooth/bluetoothd --compat

bluetoothd[20958]: Unknown key DisablePlugins for group Policy in /etc/bluetooth/main.conf
systemd[1]: Started Bluetooth service.
bluetoothd[20958]: Starting SDP server
bluetoothd[20958]: Bluetooth management interface 1.14 initialized
bluetoothd[20958]: Endpoint registered: sender=:1.206 path=/MediaEndpoint/A2DPSource
bluetoothd[20958]: Endpoint registered: sender=:1.206 path=/MediaEndpoint/A2DPSink
bluetoothd[20958]: Endpoint unregistered: sender=:1.206 path=/MediaEndpoint/A2DPSource
bluetoothd[20958]: Endpoint unregistered: sender=:1.206 path=/MediaEndpoint/A2DPSink
bluetoothd[20958]: Endpoint registered: sender=:1.206 path=/MediaEndpoint/A2DPSource
bluetoothd[20958]: Endpoint registered: sender=:1.206 path=/MediaEndpoint/A2DPSink
```

I would suggest looking into fixing that `Not enough free handles to register service` error. I've found https://bbs.archlinux.org/viewtopic.php?id=195886 saying your BT may be RF-killed, but you indicated other devices did work, so I don't think that's the case. However, someone also suggested to `rm ~/.config/pulse` and that seemed to fix it for several people, so maybe you could try that too?
